import { Metadata } from "next";

const getMetadata = (path: string, locale: string): Metadata => {
  return {
    title: `Page Title - ${path} (${locale})`,
    description: "Generated by create next app",
  };
};

export default getMetadata;
